# Generated by Django 5.2.4 on 2025-07-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
