# Generated by Django 5.2.4 on 2025-07-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_article_image_url_alter_article_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
