# Generated by Django 4.2.23 on 2025-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_newsletterlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=10),
        ),
    ]
